// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import CountdownController from "./countdown_controller"
application.register("countdown", CountdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PenaltyController from "./penalty_controller"
application.register("penalty", PenaltyController)
